module.exports={
        PRODUCT_COLLECTION:'product',
        USER_COLLECTION:'user',
        ADMIN_COLLECTION:'admin',
        CATEGORY_COLLECTION:'category',
        CART_COLLECTION:'cart',
        ORDER_COLLECTION:'order',
        WISHLIST_COLLECTION:'wishlist',
        PRODUCT_OFFERS:'productOffer',
        CATEGORY_OFFERS:'categoryOffer',
        BANNER_COLLECTION:'bannercollection',
        COUPON_COLLECTION:'coupon',
}